current/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'current'

urlpatterns = [
    path('',views.index,name='index'),
    path('(?P<event_id>[0-9]+)/',views.details,name='details'),

]

event/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('current.urls')),
]
if settings.DEBUG:
   urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

current/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    banner = models.ImageField()
    event_name = models.CharField(max_length=40)
    venue = models.CharField(max_length=40)
    date = models.DateField()
    time = models.TimeField()
    charges = models.CharField(max_length=40)
    contact = models.IntegerField()
    description=models.CharField(max_length=1000000)

    def __str__(self):
        return self.event_name

class Comment(models.Model):
    event_name = models.ForeignKey(Event, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=40)
    comment=models.CharField(max_length=40)

    def __str__(self):
        return self.user_name

current/views.py
from django.shortcuts import render,get_object_or_404
from .models import Event

# Create your views here.

def index(request):
    events = Event.objects.all()
    context = {
        'events': events
    }
    return render(request, 'current/index.html', context)


def details(request, event_id):
    event = get_object_or_404(Event, pk=event_id)

    return render(request,'current/details.html',{'event':event})


def update_event(request, event_id):
    events = get_object_or_404(Event, pk=event_id)
    return render(request, 'current/index.html',{'events':events})

current/templates/current/details.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=stylish' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Dancing Script' rel='stylesheet'>
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div class="panel panel-default" style="background-color: cornflowerblue">
                <div class="panel-body">
                    <img src="{{ event.banner.url }}" class="img img-thumbnail img-responsive" alt="">
                    <h4 style="font-family: stylish;margin: 5px" >{{event.event_name}}</h4>
                    <h4 style="font-family: stylish">{{event.venue}}</h4>
                    <h4 style="font-family: Dancing Script" >{{event.date}} {{event.time}}</h4>
                </div>
            </div>
        </div>
        <div class="col-sm-9">
             <div class="panel panel-default" style="background-color: aquamarine">
                 <div class="panel panel-header" style="background-color: cornflowerblue">
                        <h4 style="font-family: stylish"class="text-center">{{event.event_name}}</h4>
                     <p  style="font-family: Dancing Script;" class="text-center"><h6>{{event.description}}</h6> </p>
                 </div>
                     <div class="panel-body">
                         {% for home in event.comment_set.all%}
                         <h4 class="text-center" style="color: chocolate">{{home.comment}}</h4>
                         {% endfor %}

                         <h4 style="float: right; margin-left: 275px; ">{{event.venue}}</h4>
                             <h4 style=" margin-right: 400px;">{{event.charges}}</h4>
                             <h4 style="float: right">{{event.contact}}</h4>
                     </div>
                 <div class="panel panel-footer" style="float: right">

                    <a href="" class="btn btn-primary btn-sm">
                      <i class="fas fa-heart"></i>
                    </a>

                   <a href="" class="btn btn-success btn-sm">
                     <i class="fas fa-edit"></i>
                   </a>
                     <a href="" class="btn btn-danger btn-sm"
                        onclick='return confirm("are you sure you want to delete ??")'>
                        <i class="fas fa-trash"></i>
                     </a>

                  </div>
                 </div>
             </div>
        </div>


</div>

current/templates/current/index.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
<div class="container">
    <div class="row">
        {% for event in events %}
        <div class="col-sm-4">
            <div class="panel panel-default" style="background-color: bisque" >
                <div class="row">
                    <div class="col-sm-5">
                        <a href="{% url 'current:details' event.id %}">
                          <img src="{{event.banner.url}}" class="img img-thumbnail" alt=""  style="width: 150px; height: 100px;">
                        </a>
                    </div>
                    <div class="col-sm-7"><div class="caption" style="margin: 3px">
                        <h4>{{event.event_name}}</h4>
                        <h4>{{event.date}} {{event.time}}</h4>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>